print("Welcome to tip Calculator")
print("enter the bill amount")
bill = float(input())
print("enter the tip percentage you would like to give? 10, 12 or 15")
tip = float(input())
print("How many people should split the bill?")
people = int(input())
Total = bill + (bill*(tip/100))
payment = round((Total/people), 2)
pay = "{:.2f}".format(payment)
print(f"each person should pay ${pay}")
